// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OTPAuth.API.Data;

#nullable disable

namespace OTPAuth.API.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260830163003_SupportPendingOtpChallenge")]
    partial class SupportPendingOtpChallenge
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.29")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("OTPAuth.API.Entities.AuditLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("varchar(64)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasPrecision(7)
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(45)
                        .IsUnicode(false)
                        .HasColumnType("varchar(45)");

                    b.Property<Guid?>("OtpChallengeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ReasonCode")
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("varchar(64)");

                    b.Property<bool>("Success")
                        .HasColumnType("bit");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .IsDescending()
                        .HasDatabaseName("IX_AuditLogs_CreatedAt");

                    b.HasIndex("EventType", "CreatedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("IX_AuditLogs_EventType_CreatedAt");

                    b.HasIndex("UserId", "CreatedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("IX_AuditLogs_UserId_CreatedAt");

                    b.ToTable("AuditLogs", (string)null);
                });

            modelBuilder.Entity("OTPAuth.API.Entities.OtpChallenge", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<short>("AttemptCount")
                        .HasColumnType("smallint");

                    b.Property<Guid>("AuthenticationFlowId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("ConsumedAt")
                        .HasPrecision(7)
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasPrecision(7)
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<DateTimeOffset?>("ExpiresAt")
                        .HasPrecision(7)
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<DateTimeOffset>("FlowExpiresAt")
                        .HasPrecision(7)
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("bit");

                    b.Property<short>("MaxAttempts")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)5);

                    b.Property<byte[]>("OtpHash")
                        .HasColumnType("varbinary(32)");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasMaxLength(32)
                        .IsUnicode(false)
                        .HasColumnType("varchar(32)");

                    b.Property<short>("ResendCount")
                        .HasColumnType("smallint");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTimeOffset?>("SentAt")
                        .HasPrecision(7)
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("AuthenticationFlowId", "CreatedAt")
                        .HasDatabaseName("IX_OtpChallenges_AuthenticationFlowId_CreatedAt");

                    b.HasIndex("UserId", "Purpose")
                        .IsUnique()
                        .HasDatabaseName("UX_OtpChallenges_UserId_Purpose_Open")
                        .HasFilter("[IsRevoked] = 0 AND [ConsumedAt] IS NULL");

                    b.HasIndex("UserId", "Purpose", "CreatedAt")
                        .IsDescending(false, false, true)
                        .HasDatabaseName("IX_OtpChallenges_UserId_Purpose_CreatedAt");

                    b.ToTable("OtpChallenges", null, t =>
                        {
                            t.HasCheckConstraint("CK_OtpChallenges_Attempts", "[AttemptCount] >= 0 AND [AttemptCount] <= [MaxAttempts] AND [MaxAttempts] BETWEEN 1 AND 5");

                            t.HasCheckConstraint("CK_OtpChallenges_ConsumedState", "[ConsumedAt] IS NULL OR ([SentAt] IS NOT NULL AND [ConsumedAt] >= [SentAt] AND [ConsumedAt] < [ExpiresAt])");

                            t.HasCheckConstraint("CK_OtpChallenges_ExpiresAt", "[ExpiresAt] IS NULL OR ([ExpiresAt] > [CreatedAt] AND [ExpiresAt] <= [FlowExpiresAt])");

                            t.HasCheckConstraint("CK_OtpChallenges_OtpState", "([OtpHash] IS NULL AND [ExpiresAt] IS NULL AND [SentAt] IS NULL) OR ([OtpHash] IS NOT NULL AND DATALENGTH([OtpHash]) = 32 AND [ExpiresAt] IS NOT NULL AND ([SentAt] IS NULL OR ([SentAt] >= [CreatedAt] AND [SentAt] < [ExpiresAt])))");

                            t.HasCheckConstraint("CK_OtpChallenges_Purpose", "[Purpose] = 'LOGIN'");

                            t.HasCheckConstraint("CK_OtpChallenges_ResendCount", "[ResendCount] BETWEEN 0 AND 3");
                        });
                });

            modelBuilder.Entity("OTPAuth.API.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasPrecision(7)
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("nvarchar(254)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("NormalizedEmail")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("nvarchar(254)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .IsUnique()
                        .HasDatabaseName("UX_Users_NormalizedEmail");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("OTPAuth.API.Entities.AuditLog", b =>
                {
                    b.HasOne("OTPAuth.API.Entities.User", "User")
                        .WithMany("AuditLogs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("User");
                });

            modelBuilder.Entity("OTPAuth.API.Entities.OtpChallenge", b =>
                {
                    b.HasOne("OTPAuth.API.Entities.User", "User")
                        .WithMany("OtpChallenges")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("OTPAuth.API.Entities.User", b =>
                {
                    b.Navigation("AuditLogs");

                    b.Navigation("OtpChallenges");
                });
#pragma warning restore 612, 618
        }
    }
}
